name: Grid Search Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model-backend/requirements.txt

    - name: Run Grid Search
      if: contains(github.event.head_commit.message, 'grid-search-begin')
      env:
        GITHUB_TOKEN: ${{ secrets.C_PAT }}
      run: |
        python model-backend/grid-search.py
        git config --global user.email "20bce057@nirmauni.ac.in"
        git config --global user.name "Devasy23"
        git add .
        git commit -m "Add voting classifier model"
        git branch grid-search-changes  # Create a new branch
        git checkout grid-search-changes
        git push origin grid-search-changes  # Push the new branch to GitHub

    - name: Create Pull Request
      if: contains(github.event.head_commit.message, 'grid-search-begin')
      env:
        GITHUB_TOKEN: ${{ secrets.C_PAT }}
      run: |
        gh pr create --base main --head grid-search-changes --title "Grid Search Changes" --body "This pull request contains changes from the grid search."
